### ISSUE TITLE
Raise Unknown Type Issue

### ISSUE THREAD

**Issue by cunz1974** [SuperMonster003/AutoJs6-VSCode-Extension#9]
When running the script or saving the script to the pad, the following issue is raised.
java.lang.Exception: Unknown data type (0) for message dispatching

Plugin Version: v1.0.5
Autojs6 Version: 6.3.2
Issue Description: 
java.lang.Exception: Unknown data type (10) for message dispatching
	at org.autojs.autojs.runtime.ScriptRuntime.popException(ScriptRuntime.java:84)
	at org.autojs.autojs.pluginclient.JsonSocket.onMessageDispatch(JsonSocket.java:221)
	at org.autojs.autojs.pluginclient.JsonSocket.lambda$monitorMessage$0(JsonSocket.java:331)
	at org.autojs.autojs.pluginclient.JsonSocket.$r8$lambda$va2cxRhe8N9XY6l6jBcuYwu6HoA(Unknown Source:0)
	at org.autojs.autojs.pluginclient.JsonSocket$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
16:04:05.159/E: Unknown data type (0) for message dispatching

**Comment by erebusx** [comment]
虽然看不到具体的提示，但提示“Unknown data type (0) for message dispatching”，插件也是v1.0.5，autojs6也是6.3.2。
之前autojs6用6.3.0，插件没更新之前是好的。
